site_name: Suspycious

theme:
  name: material
  palette:
    # Palette toggle for dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: amber
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    # Palette toggle for light mode
    - scheme: default
      primary: amber
      accent: deep purple
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
  features:
    - content.action.view

repo_url: https://github.com/romirk/suspycious
repo_name: suspycious
edit_uri: edit/main/docs/ 

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/romirk/suspycious
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/imagifight
          
plugins:
- search
- mkdocstrings
- social
# - optimize  
